//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_GET_EDIT_DETAILS_BY_REQUIREMENT_ID_Result3
    {
        public int REQUIREMENT_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<System.DateTime> RECIEVED_DATE { get; set; }
        public Nullable<int> NO_OF_OPENINGS { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public Nullable<int> INTERVIEW_MODE_ID { get; set; }
        public string POSTING_PLACE { get; set; }
        public Nullable<int> CURRENCY_TYPE_ID { get; set; }
        public Nullable<decimal> OVERTIME { get; set; }
        public Nullable<int> TRIP_PER_YEAR { get; set; }
        public Nullable<decimal> CONTACT_PERIOD { get; set; }
        public Nullable<decimal> WORKING_HOURS { get; set; }
        public Nullable<int> LEAVES_PER_YEAR { get; set; }
        public string REMARK { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> EXPERIENCE_FROM { get; set; }
        public Nullable<decimal> EXPERIENCE_TO { get; set; }
        public Nullable<int> AGE_FROM { get; set; }
        public Nullable<int> AGE_TO { get; set; }
        public Nullable<int> BASIC_SALARY_RANGE_TO { get; set; }
        public Nullable<int> BASIC_SALARY_RANGE_FROM { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string JOB_TITLE { get; set; }
        public string GENDER_CODES { get; set; }
        public string LANGUAGE_ID { get; set; }
        public string EDUCATION_TYPE_ID { get; set; }
        public string RELIGION_ID { get; set; }
        public string DESIGNATION_ID { get; set; }
        public string INDUSTRY_ID { get; set; }
        public string SPECIALIZATION_ID { get; set; }
        public string CERTIFICATION_ID { get; set; }
        public string ALLOWANCE_ID { get; set; }
    }
}
