//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_STATUS_SEARCH_CANDIDATE_Result4
    {
        public string REGISTRATION_NO { get; set; }
        public string REGISTRATION_DATE { get; set; }
        public string CANDIDATE_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string CONTACT_NO { get; set; }
    }
}
