//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_USER_LOGIN_DETAILS_Result1
    {
        public string REGISTRATION_NO { get; set; }
        public int USER_TYPE_ID { get; set; }
        public string USER_IMAGE_PATH { get; set; }
        public string NAME { get; set; }
    }
}
