//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_GET_ALL_STATES_Result1
    {
        public string STATE_CODE { get; set; }
        public string STATE_NAME { get; set; }
        public string COUNTRY_NAME { get; set; }
        public int ID { get; set; }
        public string COUNTRY_CODE { get; set; }
    }
}
