//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_USER_ADDUPDATE_REQUIREMENT_Result2
    {
        public int USER_REQUIREMENT_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public int REQUIREMENT_ID { get; set; }
        public string REQUIREMENT { get; set; }
        public int CANDIDATE_STATUS { get; set; }
        public string STATUS_NAME { get; set; }
        public bool CURRENT_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
