//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_GETUSER_BYUSERTYPE_Result1
    {
        public string REGISTRATION_NO { get; set; }
        public string NAME { get; set; }
    }
}
