//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_GET_ADVERTISEMENT_DATA_Result5
    {
        public int ADV_ID { get; set; }
        public string PAPER_NAME { get; set; }
        public string AD_AGENCY_NAME { get; set; }
        public Nullable<decimal> EXPENSES { get; set; }
        public Nullable<int> REQUIREMENT_ID { get; set; }
        public Nullable<System.DateTime> ADV_DATE { get; set; }
        public string FILE_PATH { get; set; }
        public string REQUIREMENT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
