//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    
    public partial class PROC_CANDIDATE_STATUS_SEARCH_Result1
    {
        public string REGISTRATION_NO { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CANDIDATE_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string GENDER_NAME { get; set; }
        public string GENDER_CODE { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<int> AGE { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public string MARITAL_STATUS { get; set; }
        public Nullable<int> MARITAL_STATUS_ID { get; set; }
        public string NATIONALITY { get; set; }
        public Nullable<int> NATIONALITY_ID { get; set; }
        public string RELIGION_NAME { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public string CONTACT_NO { get; set; }
        public string USER_EMAIL { get; set; }
        public string SOURCE_NAME { get; set; }
        public Nullable<int> SOURCE_ID { get; set; }
        public string AVAILING_TYPE { get; set; }
        public Nullable<int> AVAILING_TYPE_ID { get; set; }
        public string REFERRER_NAME { get; set; }
        public Nullable<int> REQUIREMENT_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string CURRENT_LOCATION { get; set; }
        public string VISA_NUMBER { get; set; }
        public Nullable<int> VISA_ID { get; set; }
        public bool LOGIN_ACCESS { get; set; }
        public string REMARK { get; set; }
        public string TOTAL_WORK_EXPERIENCE { get; set; }
        public string TOTAL_GULF_EXPERIENCE { get; set; }
        public string WORK_REMARK { get; set; }
        public string SKILLS { get; set; }
        public string WEBSITE { get; set; }
        public string SKYPE { get; set; }
        public string CONTACT_REMARK { get; set; }
    }
}
