//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_EMAIL_ADDRESS
    {
        public int USER_EMAIL_ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string USER_EMAIL { get; set; }
    }
}
