//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_DOCUMENTS
    {
        public int DOCUMENT_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string DOCUMENT_TYPE_ID { get; set; }
        public string DOCUMENT_PATH { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TBL_USER_DETAILS TBL_USER_DETAILS { get; set; }
    }
}
