//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_EDUCATION_DETAILS
    {
        public int USER_EDUCATION_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public Nullable<int> EDUCATION_TYPE_ID { get; set; }
        public Nullable<int> SPECIALIZATION_TYPE_ID { get; set; }
        public string UNIVERSITY_ID { get; set; }
        public string UNIVERSITY_YEAR_OF_PASSING { get; set; }
        public Nullable<bool> IS_HIGHEST_QUALIFICATION { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
