//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LMS_MENU
    {
        public int LMS_MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_TITLE { get; set; }
        public string MENU_URL { get; set; }
        public Nullable<int> PARENT_MENU_ID { get; set; }
        public Nullable<bool> IS_PARENT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string REMARK { get; set; }
        public string PAGE_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string MENU_ICON { get; set; }
    }
}
