//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VISA_ENDORSEMENT
    {
        public int VisaEndorsementId { get; set; }
        public int USER_REQUIREMENT_ID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<int> SubmissionStatusID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string VisaEndorsementFilePath { get; set; }
    
        public virtual TBL_USER_REQUIREMENT TBL_USER_REQUIREMENT { get; set; }
    }
}
