//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REQUIREMENT_ALLOWANCE
    {
        public int REQUIREMENT_ALLOWANCE_ID { get; set; }
        public Nullable<int> ALLOWANCE_ID { get; set; }
        public Nullable<int> REQUIRMENT_ID { get; set; }
        public Nullable<bool> IS_INCLUDED { get; set; }
        public Nullable<bool> IS_ALLOWANCE { get; set; }
        public Nullable<decimal> ALLOWANCE_AMOUNT { get; set; }
        public Nullable<bool> IS_NOT_APPLICABLE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> ALLOWANCE_TYPE_ID { get; set; }
    
        public virtual TBL_ALLOWANCE_MASTER TBL_ALLOWANCE_MASTER { get; set; }
        public virtual TBL_ALLOWANCE_TYPE_MASTER TBL_ALLOWANCE_TYPE_MASTER { get; set; }
        public virtual TBL_REQUIREMENT_DETAILS TBL_REQUIREMENT_DETAILS { get; set; }
    }
}
