//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMIGRATION
    {
        public int EMIGRATION_ID { get; set; }
        public Nullable<int> USER_REQUIREMENT_ID { get; set; }
        public string FE_NO { get; set; }
        public string PT_NO { get; set; }
        public string DM_NO { get; set; }
        public Nullable<System.DateTime> DM_DATE { get; set; }
        public string POLICY_NO { get; set; }
        public Nullable<System.DateTime> POLICY_DATE { get; set; }
        public Nullable<decimal> POLICY_AMOUNT { get; set; }
        public string POLICY_COMPANYNAME { get; set; }
        public string POLICY_ATTACHMENT { get; set; }
        public Nullable<System.DateTime> SUBMISSION_DATE { get; set; }
        public string EMIGRATION_CLEARANCENO { get; set; }
        public string EMIGRATION_ATTACHMENT { get; set; }
        public string POE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> IS_ECR { get; set; }
    
        public virtual TBL_USER_REQUIREMENT TBL_USER_REQUIREMENT { get; set; }
    }
}
