//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTRATION_COUNTER
    {
        public int COUNTER_ID { get; set; }
        public string COUNTER_FOR { get; set; }
        public string COUNTER_PREFIX { get; set; }
        public int CURRENT_VALUE { get; set; }
    }
}
