//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_ADDRESS
    {
        public int USER_ADDRESS_ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public int ADDRESS_TYPE_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY_CODE { get; set; }
        public string USER_VILLAGE { get; set; }
        public string USER_PINCODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string STATE_CODE { get; set; }
    }
}
