//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_DRIVING_LICENCE_DETAILS
    {
        public int DRIVING_LICENCE_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string DRIVING_LICENCE_NUMBER { get; set; }
        public string PLACE_OF_ISSUE { get; set; }
        public Nullable<System.DateTime> DATE_OF_ISSUE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<int> VEHICLE_TYPE_ID { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
