//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VISA_MASTER
    {
        public int VISA_ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string CIVILIAN_NUMBER { get; set; }
        public string VISA_NUMBER { get; set; }
        public string PLACE_OF_ENDORSEMENT { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public System.DateTime RECIEVED_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
