//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TICKET
    {
        public int TicketID { get; set; }
        public int USER_REQUIREMENT_ID { get; set; }
        public Nullable<int> AirlinesID { get; set; }
        public string OtherAirlines { get; set; }
        public Nullable<bool> IsDirect { get; set; }
        public string PnrNumber { get; set; }
        public string TicketNumber { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string DepartureCityCode { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string DestinationCityCode { get; set; }
        public Nullable<System.DateTime> ArivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public string ReportPath { get; set; }
        public string Remark { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual TBL_USER_REQUIREMENT TBL_USER_REQUIREMENT { get; set; }
    }
}
