//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERROR_LOG
    {
        public int ID { get; set; }
        public string PAGE_NAME { get; set; }
        public string PAGE_URL { get; set; }
        public string METHOD_NAME { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string INNER_EXCEPTION_MESSAGE { get; set; }
        public string USER_IP { get; set; }
        public string USER_CODE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
