//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PASSPORT_DETAILS
    {
        public int PASSPORT_ID { get; set; }
        public string REGISTATION_NUMBER { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_ISSUE { get; set; }
        public string PLACE_OF_ISSUE { get; set; }
        public Nullable<System.DateTime> DATE_OF_EXPIRY { get; set; }
        public Nullable<bool> EMIGRATION_CLEARANCE_REQUIRED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
