//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_EXPERIENCE
    {
        public int EXPERIENCE_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string USER_COMPANY_NAME { get; set; }
        public Nullable<bool> IS_CURRENT_COMPANY { get; set; }
        public Nullable<int> DESIGNATION_ID { get; set; }
        public Nullable<int> INDUSTRY_ID { get; set; }
        public string CITY_CODE { get; set; }
        public Nullable<decimal> TOTAL_WORK_EXPERIENCE { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> WORK_PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> WORK_PERIOD_TO { get; set; }
        public string STATE_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
    }
}
