//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REQUIREMENT_RELIGION
    {
        public int REQUIREMENT_RELIIGION_ID { get; set; }
        public Nullable<int> REQUIREMENT_ID { get; set; }
        public string RELIGION_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual TBL_REQUIREMENT_DETAILS TBL_REQUIREMENT_DETAILS { get; set; }
    }
}
