//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TASK_FOLLOWUP
    {
        public int TASK_FOLLOWUP_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public string TASK_COMMENT { get; set; }
        public Nullable<decimal> PERC_COMPLETED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
