//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REQUIREMENT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_REQUIREMENT_DETAILS()
        {
            this.TBL_INTERVIEW = new HashSet<TBL_INTERVIEW>();
            this.TBL_REQUIREMENT_ALLOWANCE = new HashSet<TBL_REQUIREMENT_ALLOWANCE>();
            this.TBL_REQUIREMENT_GENDER = new HashSet<TBL_REQUIREMENT_GENDER>();
            this.TBL_REQUIREMENT_LANGUAGE = new HashSet<TBL_REQUIREMENT_LANGUAGE>();
            this.TBL_REQUIREMENT_RELIGION = new HashSet<TBL_REQUIREMENT_RELIGION>();
            this.TBL_USER_REQUIREMENT = new HashSet<TBL_USER_REQUIREMENT>();
        }
    
        public int REQUIREMENT_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public Nullable<System.DateTime> RECIEVED_DATE { get; set; }
        public Nullable<int> NO_OF_OPENINGS { get; set; }
        public Nullable<decimal> EXPERIENCE { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public Nullable<int> INTERVIEW_MODE_ID { get; set; }
        public Nullable<int> SPECIALIZATION_ID { get; set; }
        public string POSTING_PLACE { get; set; }
        public Nullable<int> CURRENCY_TYPE_ID { get; set; }
        public Nullable<int> BASIC_RANGE { get; set; }
        public Nullable<decimal> OVERTIME { get; set; }
        public Nullable<int> TRIP_PER_YEAR { get; set; }
        public Nullable<decimal> CONTACT_PERIOD { get; set; }
        public Nullable<decimal> WORKING_HOURS { get; set; }
        public Nullable<int> LEAVES_PER_YEAR { get; set; }
        public string REMARK { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> EXPERIENCE_FROM { get; set; }
        public Nullable<decimal> EXPERIENCE_TO { get; set; }
        public Nullable<int> AGE_FROM { get; set; }
        public Nullable<int> AGE_TO { get; set; }
        public Nullable<int> BASIC_SALARY_RANGE_TO { get; set; }
        public Nullable<int> BASIC_SALARY_RANGE_FROM { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string STATUS_ID { get; set; }
        public string JOB_TITLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVIEW> TBL_INTERVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REQUIREMENT_ALLOWANCE> TBL_REQUIREMENT_ALLOWANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REQUIREMENT_GENDER> TBL_REQUIREMENT_GENDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REQUIREMENT_LANGUAGE> TBL_REQUIREMENT_LANGUAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REQUIREMENT_RELIGION> TBL_REQUIREMENT_RELIGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USER_REQUIREMENT> TBL_USER_REQUIREMENT { get; set; }
    }
}
