//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVIEW
    {
        public int InterviewID { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Agent_ID { get; set; }
        public Nullable<int> RequirementID { get; set; }
        public int InterviewModeId { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public string InterviewVenue { get; set; }
        public Nullable<decimal> InterviewExpenses { get; set; }
        public string InterviewRemark { get; set; }
        public bool IsSelected { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual TBL_INTERVIEW_MODE_MASTER TBL_INTERVIEW_MODE_MASTER { get; set; }
        public virtual TBL_USER_DETAILS TBL_USER_DETAILS { get; set; }
        public virtual TBL_REQUIREMENT_DETAILS TBL_REQUIREMENT_DETAILS { get; set; }
    }
}
