//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_LANGUAGE
    {
        public int USER_LANGUAGE_ID { get; set; }
        public int LANGUAGE_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public bool IS_READ { get; set; }
        public bool IS_WRITE { get; set; }
        public bool IS_SPEAK { get; set; }
    }
}
