//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_CERTIFICATION
    {
        public int USER_CERTIFICATION_ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string CERTIFICATION { get; set; }
        public Nullable<int> CERTIFICATION_LEVEL { get; set; }
        public string INSTITUTE { get; set; }
        public Nullable<int> YEAR_OF_PASSING { get; set; }
    }
}
