//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_TYPE
    {
        public int USER_TYPE_ID { get; set; }
        public string USER_TYPE { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
