//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONNECTED_TICKETDETAILS
    {
        public int ConnectTicketID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string PnrNumber { get; set; }
        public string TicketNumber { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string DepartureCityCode { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string DestinationCityCode { get; set; }
    }
}
