//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_VISA_DETAILS
    {
        public int USER_VISA_ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public Nullable<int> VISA_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
