//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_PERSONAL_DETAILS
    {
        public string REGISTRATION_NO { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string MOTHER_NAME { get; set; }
        public string GENDER_CODE { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public Nullable<int> MARITAL_STATUS_ID { get; set; }
        public Nullable<int> NATIONALITY_ID { get; set; }
        public string CURRENT_LOCATION { get; set; }
        public Nullable<int> RELIGION_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
