//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIROERP.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArbabTravelsERPEntities : DbContext
    {
        public ArbabTravelsERPEntities()
            : base("name=ArbabTravelsERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_AD_MEDIUM_MASTER> TBL_AD_MEDIUM_MASTER { get; set; }
        public virtual DbSet<TBL_ADDRESS_TYPE_MASTER> TBL_ADDRESS_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_ALLOWANCE_MASTER> TBL_ALLOWANCE_MASTER { get; set; }
        public virtual DbSet<TBL_ALLOWANCE_TYPE_MASTER> TBL_ALLOWANCE_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_AVAILING_TYPE_MASTER> TBL_AVAILING_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_CAREER_STATUS_MASTER> TBL_CAREER_STATUS_MASTER { get; set; }
        public virtual DbSet<TBL_COMPANY_MASTER> TBL_COMPANY_MASTER { get; set; }
        public virtual DbSet<TBL_CONNECTED_TICKETDETAILS> TBL_CONNECTED_TICKETDETAILS { get; set; }
        public virtual DbSet<TBL_CONTACT_TYPE_MASTER> TBL_CONTACT_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_CURRENCY_MASTER> TBL_CURRENCY_MASTER { get; set; }
        public virtual DbSet<TBL_EDUCATION_TYPE_MASTER> TBL_EDUCATION_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_EMAIL_TYPE_MASTER> TBL_EMAIL_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_ERROR_LOG> TBL_ERROR_LOG { get; set; }
        public virtual DbSet<TBL_GENDER_MASTER> TBL_GENDER_MASTER { get; set; }
        public virtual DbSet<TBL_INDUSTRY_MASTER> TBL_INDUSTRY_MASTER { get; set; }
        public virtual DbSet<TBL_INTERVIEW> TBL_INTERVIEW { get; set; }
        public virtual DbSet<TBL_INTERVIEW_MODE_MASTER> TBL_INTERVIEW_MODE_MASTER { get; set; }
        public virtual DbSet<TBL_LANGUAGE_MASTER> TBL_LANGUAGE_MASTER { get; set; }
        public virtual DbSet<TBL_MARITAL_STATUS_MASTER> TBL_MARITAL_STATUS_MASTER { get; set; }
        public virtual DbSet<TBL_MEDICAL_STATUS> TBL_MEDICAL_STATUS { get; set; }
        public virtual DbSet<TBL_PASSPORT_DETAILS> TBL_PASSPORT_DETAILS { get; set; }
        public virtual DbSet<TBL_PREFIX_MASTER> TBL_PREFIX_MASTER { get; set; }
        public virtual DbSet<TBL_REGISTRATION_COUNTER> TBL_REGISTRATION_COUNTER { get; set; }
        public virtual DbSet<TBL_RELIGION_MASTER> TBL_RELIGION_MASTER { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_ALLOWANCE> TBL_REQUIREMENT_ALLOWANCE { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_GENDER> TBL_REQUIREMENT_GENDER { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_LANGUAGE> TBL_REQUIREMENT_LANGUAGE { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_RELIGION> TBL_REQUIREMENT_RELIGION { get; set; }
        public virtual DbSet<TBL_REQUIRMENT_EDUCATION_TYPE> TBL_REQUIRMENT_EDUCATION_TYPE { get; set; }
        public virtual DbSet<TBL_REQUIRMENT_INDUSTRY> TBL_REQUIRMENT_INDUSTRY { get; set; }
        public virtual DbSet<TBL_REQUIRMENT_SPECIALIZATION> TBL_REQUIRMENT_SPECIALIZATION { get; set; }
        public virtual DbSet<TBL_RESUME_VIEW> TBL_RESUME_VIEW { get; set; }
        public virtual DbSet<TBL_ROLE_MASTER> TBL_ROLE_MASTER { get; set; }
        public virtual DbSet<TBL_SOURCE_MASTER> TBL_SOURCE_MASTER { get; set; }
        public virtual DbSet<TBL_SPECIALIZATION_MASTER> TBL_SPECIALIZATION_MASTER { get; set; }
        public virtual DbSet<TBL_STATUS_MASTER> TBL_STATUS_MASTER { get; set; }
        public virtual DbSet<TBL_TASK_FOLLOWUP> TBL_TASK_FOLLOWUP { get; set; }
        public virtual DbSet<TBL_TASK_MASTER> TBL_TASK_MASTER { get; set; }
        public virtual DbSet<TBL_UNIVERSITY_MASTER> TBL_UNIVERSITY_MASTER { get; set; }
        public virtual DbSet<TBL_USER_ADDRESS> TBL_USER_ADDRESS { get; set; }
        public virtual DbSet<TBL_USER_CERTIFICATION> TBL_USER_CERTIFICATION { get; set; }
        public virtual DbSet<TBL_USER_CONTACTS> TBL_USER_CONTACTS { get; set; }
        public virtual DbSet<TBL_USER_DOCUMENT_MASTER> TBL_USER_DOCUMENT_MASTER { get; set; }
        public virtual DbSet<TBL_USER_DRIVING_LICENCE_DETAILS> TBL_USER_DRIVING_LICENCE_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_EDUCATION_DETAILS> TBL_USER_EDUCATION_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_EMAIL_ADDRESS> TBL_USER_EMAIL_ADDRESS { get; set; }
        public virtual DbSet<TBL_USER_EXPERIENCE> TBL_USER_EXPERIENCE { get; set; }
        public virtual DbSet<TBL_USER_LANGUAGE> TBL_USER_LANGUAGE { get; set; }
        public virtual DbSet<TBL_USER_MENU_MAPPING> TBL_USER_MENU_MAPPING { get; set; }
        public virtual DbSet<TBL_USER_PERSONAL_DETAILS> TBL_USER_PERSONAL_DETAILS { get; set; }
        public virtual DbSet<TBL_USER_REGISTRATION> TBL_USER_REGISTRATION { get; set; }
        public virtual DbSet<TBL_USER_TYPE> TBL_USER_TYPE { get; set; }
        public virtual DbSet<TBL_USER_VISA_DETAILS> TBL_USER_VISA_DETAILS { get; set; }
        public virtual DbSet<TBL_VEHICLE_TYPE> TBL_VEHICLE_TYPE { get; set; }
        public virtual DbSet<TBL_VISA_MASTER> TBL_VISA_MASTER { get; set; }
        public virtual DbSet<TBL_VISA_SUBMISSION_STATUS> TBL_VISA_SUBMISSION_STATUS { get; set; }
        public virtual DbSet<TBL_BRANCH_MASTER> TBL_BRANCH_MASTER { get; set; }
        public virtual DbSet<TBL_LMS_MENU> TBL_LMS_MENU { get; set; }
        public virtual DbSet<TBL_NATIONALITY_MASTER> TBL_NATIONALITY_MASTER { get; set; }
        public virtual DbSet<TBL_PORTAL_MASTER> TBL_PORTAL_MASTER { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_TYPE_MASTER> TBL_REQUIREMENT_TYPE_MASTER { get; set; }
        public virtual DbSet<TBL_SAVE_TO_FOLDER_DETAILS> TBL_SAVE_TO_FOLDER_DETAILS { get; set; }
        public virtual DbSet<Tmp_TBL_TASK_MASTER> Tmp_TBL_TASK_MASTER { get; set; }
        public virtual DbSet<TBL_COUNTRY_MASTER> TBL_COUNTRY_MASTER { get; set; }
        public virtual DbSet<TBL_AIRLINES_MASTER> TBL_AIRLINES_MASTER { get; set; }
        public virtual DbSet<TBL_CERTIFICATION_MASTER> TBL_CERTIFICATION_MASTER { get; set; }
        public virtual DbSet<TBL_DESIGNATION_MASTER> TBL_DESIGNATION_MASTER { get; set; }
        public virtual DbSet<TBL_USER_DETAILS> TBL_USER_DETAILS { get; set; }
        public virtual DbSet<TBL_REQUIRMENT_CERTIFICATION> TBL_REQUIRMENT_CERTIFICATION { get; set; }
        public virtual DbSet<TBL_MEDICAL> TBL_MEDICAL { get; set; }
        public virtual DbSet<TBL_MOFA> TBL_MOFA { get; set; }
        public virtual DbSet<TBL_POLICY> TBL_POLICY { get; set; }
        public virtual DbSet<TBL_TICKET> TBL_TICKET { get; set; }
        public virtual DbSet<TBL_VISA_ENDORSEMENT> TBL_VISA_ENDORSEMENT { get; set; }
        public virtual DbSet<TBL_USER_REQUIREMENT> TBL_USER_REQUIREMENT { get; set; }
        public virtual DbSet<TBL_EMIGRATION> TBL_EMIGRATION { get; set; }
        public virtual DbSet<TBL_ADVERTISEMENT_MASTER> TBL_ADVERTISEMENT_MASTER { get; set; }
        public virtual DbSet<TBL_REQUIREMENT_DETAILS> TBL_REQUIREMENT_DETAILS { get; set; }
        public virtual DbSet<TBL_CITY_MASTER> TBL_CITY_MASTER { get; set; }
        public virtual DbSet<TBL_STATE_MASTER> TBL_STATE_MASTER { get; set; }
        public virtual DbSet<TBL_USER_DOCUMENTS> TBL_USER_DOCUMENTS { get; set; }
    
        public virtual ObjectResult<string> PROC_VISA_MASTER(string rEGISTRATION_NUMBER, string vISA_NUMBER, string pLACE_OF_ENDORSEMENT, Nullable<System.DateTime> iSSUE_DATE, Nullable<System.DateTime> eXPIRY_DATE, Nullable<System.DateTime> rECIEVED_DATE, string fILE_NAME, string fILE_PATH, string rEMARK, string cREATED_BY, string pURPOSE, string cONDITIONAL_OPERATOR)
        {
            var rEGISTRATION_NUMBERParameter = rEGISTRATION_NUMBER != null ?
                new ObjectParameter("REGISTRATION_NUMBER", rEGISTRATION_NUMBER) :
                new ObjectParameter("REGISTRATION_NUMBER", typeof(string));
    
            var vISA_NUMBERParameter = vISA_NUMBER != null ?
                new ObjectParameter("VISA_NUMBER", vISA_NUMBER) :
                new ObjectParameter("VISA_NUMBER", typeof(string));
    
            var pLACE_OF_ENDORSEMENTParameter = pLACE_OF_ENDORSEMENT != null ?
                new ObjectParameter("PLACE_OF_ENDORSEMENT", pLACE_OF_ENDORSEMENT) :
                new ObjectParameter("PLACE_OF_ENDORSEMENT", typeof(string));
    
            var iSSUE_DATEParameter = iSSUE_DATE.HasValue ?
                new ObjectParameter("ISSUE_DATE", iSSUE_DATE) :
                new ObjectParameter("ISSUE_DATE", typeof(System.DateTime));
    
            var eXPIRY_DATEParameter = eXPIRY_DATE.HasValue ?
                new ObjectParameter("EXPIRY_DATE", eXPIRY_DATE) :
                new ObjectParameter("EXPIRY_DATE", typeof(System.DateTime));
    
            var rECIEVED_DATEParameter = rECIEVED_DATE.HasValue ?
                new ObjectParameter("RECIEVED_DATE", rECIEVED_DATE) :
                new ObjectParameter("RECIEVED_DATE", typeof(System.DateTime));
    
            var fILE_NAMEParameter = fILE_NAME != null ?
                new ObjectParameter("FILE_NAME", fILE_NAME) :
                new ObjectParameter("FILE_NAME", typeof(string));
    
            var fILE_PATHParameter = fILE_PATH != null ?
                new ObjectParameter("FILE_PATH", fILE_PATH) :
                new ObjectParameter("FILE_PATH", typeof(string));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var cREATED_BYParameter = cREATED_BY != null ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(string));
    
            var pURPOSEParameter = pURPOSE != null ?
                new ObjectParameter("PURPOSE", pURPOSE) :
                new ObjectParameter("PURPOSE", typeof(string));
    
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_VISA_MASTER", rEGISTRATION_NUMBERParameter, vISA_NUMBERParameter, pLACE_OF_ENDORSEMENTParameter, iSSUE_DATEParameter, eXPIRY_DATEParameter, rECIEVED_DATEParameter, fILE_NAMEParameter, fILE_PATHParameter, rEMARKParameter, cREATED_BYParameter, pURPOSEParameter, cONDITIONAL_OPERATORParameter);
        }
    
        public virtual ObjectResult<PROC_ALL_MASTER_Result> PROC_ALL_MASTER(string cONDITIONAL_OPERATOR, string rEGISTRATION_NO)
        {
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_ALL_MASTER_Result>("PROC_ALL_MASTER", cONDITIONAL_OPERATORParameter, rEGISTRATION_NOParameter);
        }
    
        public virtual ObjectResult<PROC_VISA_GETALLVISA_Result2> PROC_VISA_GETALLVISA(string cREATED_BY, Nullable<int> vISA_ID, string vISA_NUMBER, Nullable<System.DateTime> fROMDATE, Nullable<System.DateTime> tODATE, string cONDITIONAL_OPERATOR)
        {
            var cREATED_BYParameter = cREATED_BY != null ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(string));
    
            var vISA_IDParameter = vISA_ID.HasValue ?
                new ObjectParameter("VISA_ID", vISA_ID) :
                new ObjectParameter("VISA_ID", typeof(int));
    
            var vISA_NUMBERParameter = vISA_NUMBER != null ?
                new ObjectParameter("VISA_NUMBER", vISA_NUMBER) :
                new ObjectParameter("VISA_NUMBER", typeof(string));
    
            var fROMDATEParameter = fROMDATE.HasValue ?
                new ObjectParameter("FROMDATE", fROMDATE) :
                new ObjectParameter("FROMDATE", typeof(System.DateTime));
    
            var tODATEParameter = tODATE.HasValue ?
                new ObjectParameter("TODATE", tODATE) :
                new ObjectParameter("TODATE", typeof(System.DateTime));
    
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_VISA_GETALLVISA_Result2>("PROC_VISA_GETALLVISA", cREATED_BYParameter, vISA_IDParameter, vISA_NUMBERParameter, fROMDATEParameter, tODATEParameter, cONDITIONAL_OPERATORParameter);
        }
    
        public virtual ObjectResult<PROC_GET_REQUIREMENT_Result1> PROC_GET_REQUIREMENT(Nullable<int> requirementId)
        {
            var requirementIdParameter = requirementId.HasValue ?
                new ObjectParameter("RequirementId", requirementId) :
                new ObjectParameter("RequirementId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_REQUIREMENT_Result1>("PROC_GET_REQUIREMENT", requirementIdParameter);
        }
    
        public virtual ObjectResult<GET_COUNTRY_STATE_CITY_Result> GET_COUNTRY_STATE_CITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_COUNTRY_STATE_CITY_Result>("GET_COUNTRY_STATE_CITY");
        }
    
        public virtual ObjectResult<GET_DESIGNATION_BYINDUSTRY_Result> GET_DESIGNATION_BYINDUSTRY(string iNDUSTRY_ID)
        {
            var iNDUSTRY_IDParameter = iNDUSTRY_ID != null ?
                new ObjectParameter("INDUSTRY_ID", iNDUSTRY_ID) :
                new ObjectParameter("INDUSTRY_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DESIGNATION_BYINDUSTRY_Result>("GET_DESIGNATION_BYINDUSTRY", iNDUSTRY_IDParameter);
        }
    
        public virtual ObjectResult<GET_SPECIALIZATION_BYEDUCATION_Result> GET_SPECIALIZATION_BYEDUCATION(string eDUCATION_TYPE_ID)
        {
            var eDUCATION_TYPE_IDParameter = eDUCATION_TYPE_ID != null ?
                new ObjectParameter("EDUCATION_TYPE_ID", eDUCATION_TYPE_ID) :
                new ObjectParameter("EDUCATION_TYPE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SPECIALIZATION_BYEDUCATION_Result>("GET_SPECIALIZATION_BYEDUCATION", eDUCATION_TYPE_IDParameter);
        }
    
        public virtual ObjectResult<PROC_GETUSER_BYUSERTYPE_Result1> PROC_GETUSER_BYUSERTYPE(Nullable<int> uSER_TYPE_ID)
        {
            var uSER_TYPE_IDParameter = uSER_TYPE_ID.HasValue ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GETUSER_BYUSERTYPE_Result1>("PROC_GETUSER_BYUSERTYPE", uSER_TYPE_IDParameter);
        }
    
        public virtual ObjectResult<PROC_GET_LAYOUT_MENU_Result> PROC_GET_LAYOUT_MENU(string uSER_TYPE_ID)
        {
            var uSER_TYPE_IDParameter = uSER_TYPE_ID != null ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_LAYOUT_MENU_Result>("PROC_GET_LAYOUT_MENU", uSER_TYPE_IDParameter);
        }
    
        public virtual ObjectResult<PROC_GET_MENU_BY_SELECTED_USER_Result> PROC_GET_MENU_BY_SELECTED_USER(string uSER_TYPE_ID)
        {
            var uSER_TYPE_IDParameter = uSER_TYPE_ID != null ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_MENU_BY_SELECTED_USER_Result>("PROC_GET_MENU_BY_SELECTED_USER", uSER_TYPE_IDParameter);
        }
    
        public virtual int PROC_ADD_DELETE_MENU_FOR_USERTYPE(Nullable<int> mENU_ID, string uSER_TYPE_ID, string cREATED_BY, string cONDITIONAL_OPERATOR)
        {
            var mENU_IDParameter = mENU_ID.HasValue ?
                new ObjectParameter("MENU_ID", mENU_ID) :
                new ObjectParameter("MENU_ID", typeof(int));
    
            var uSER_TYPE_IDParameter = uSER_TYPE_ID != null ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(string));
    
            var cREATED_BYParameter = cREATED_BY != null ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(string));
    
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_ADD_DELETE_MENU_FOR_USERTYPE", mENU_IDParameter, uSER_TYPE_IDParameter, cREATED_BYParameter, cONDITIONAL_OPERATORParameter);
        }
    
        public virtual ObjectResult<PROC_GET_CERTIFICATION_DETAILS_Result> PROC_GET_CERTIFICATION_DETAILS(string rEGISTRATION_NO)
        {
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_CERTIFICATION_DETAILS_Result>("PROC_GET_CERTIFICATION_DETAILS", rEGISTRATION_NOParameter);
        }
    
        public virtual ObjectResult<PROC_GET_EDUCATION_DETAILS_Result> PROC_GET_EDUCATION_DETAILS(string rEGISTRATION_NO)
        {
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_EDUCATION_DETAILS_Result>("PROC_GET_EDUCATION_DETAILS", rEGISTRATION_NOParameter);
        }
    
        public virtual ObjectResult<string> PROC_GET_CANDIDATE_NAME_BASED_ON_PASPPORT_NO(Nullable<int> uSER_REQUIREMENT_ID)
        {
            var uSER_REQUIREMENT_IDParameter = uSER_REQUIREMENT_ID.HasValue ?
                new ObjectParameter("USER_REQUIREMENT_ID", uSER_REQUIREMENT_ID) :
                new ObjectParameter("USER_REQUIREMENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_GET_CANDIDATE_NAME_BASED_ON_PASPPORT_NO", uSER_REQUIREMENT_IDParameter);
        }
    
        public virtual int PROC_UPDATE_USER_STATUS(Nullable<int> uSER_REQUIREMENT_ID, Nullable<int> status)
        {
            var uSER_REQUIREMENT_IDParameter = uSER_REQUIREMENT_ID.HasValue ?
                new ObjectParameter("USER_REQUIREMENT_ID", uSER_REQUIREMENT_ID) :
                new ObjectParameter("USER_REQUIREMENT_ID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_USER_STATUS", uSER_REQUIREMENT_IDParameter, statusParameter);
        }
    
        public virtual ObjectResult<PROC_CANDIDATE_STATUS_SEARCH_Result1> PROC_CANDIDATE_STATUS_SEARCH(string rEGISTRATION_NO, string cONDITIONAL_OPERATOR)
        {
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CANDIDATE_STATUS_SEARCH_Result1>("PROC_CANDIDATE_STATUS_SEARCH", rEGISTRATION_NOParameter, cONDITIONAL_OPERATORParameter);
        }
    
        public virtual ObjectResult<PROC_GET_PASSPORT_DETAILS_Result3> PROC_GET_PASSPORT_DETAILS(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_PASSPORT_DETAILS_Result3>("PROC_GET_PASSPORT_DETAILS", statusParameter);
        }
    
        public virtual ObjectResult<PROC_STATUS_SEARCH_CANDIDATE_Result4> PROC_STATUS_SEARCH_CANDIDATE(string rEGISTRATION_NUMBER, string pASSPORT_NUMBER, string cANDIDATE_NAME, Nullable<System.DateTime> dATE_OF_BIRTH, string cONTACT_NUMBER, Nullable<int> uSER_TYPE_ID)
        {
            var rEGISTRATION_NUMBERParameter = rEGISTRATION_NUMBER != null ?
                new ObjectParameter("REGISTRATION_NUMBER", rEGISTRATION_NUMBER) :
                new ObjectParameter("REGISTRATION_NUMBER", typeof(string));
    
            var pASSPORT_NUMBERParameter = pASSPORT_NUMBER != null ?
                new ObjectParameter("PASSPORT_NUMBER", pASSPORT_NUMBER) :
                new ObjectParameter("PASSPORT_NUMBER", typeof(string));
    
            var cANDIDATE_NAMEParameter = cANDIDATE_NAME != null ?
                new ObjectParameter("CANDIDATE_NAME", cANDIDATE_NAME) :
                new ObjectParameter("CANDIDATE_NAME", typeof(string));
    
            var dATE_OF_BIRTHParameter = dATE_OF_BIRTH.HasValue ?
                new ObjectParameter("DATE_OF_BIRTH", dATE_OF_BIRTH) :
                new ObjectParameter("DATE_OF_BIRTH", typeof(System.DateTime));
    
            var cONTACT_NUMBERParameter = cONTACT_NUMBER != null ?
                new ObjectParameter("CONTACT_NUMBER", cONTACT_NUMBER) :
                new ObjectParameter("CONTACT_NUMBER", typeof(string));
    
            var uSER_TYPE_IDParameter = uSER_TYPE_ID.HasValue ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_STATUS_SEARCH_CANDIDATE_Result4>("PROC_STATUS_SEARCH_CANDIDATE", rEGISTRATION_NUMBERParameter, pASSPORT_NUMBERParameter, cANDIDATE_NAMEParameter, dATE_OF_BIRTHParameter, cONTACT_NUMBERParameter, uSER_TYPE_IDParameter);
        }
    
        public virtual ObjectResult<PROC_GET_AGENT_NAME_Result1> PROC_GET_AGENT_NAME()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_AGENT_NAME_Result1>("PROC_GET_AGENT_NAME");
        }
    
        public virtual ObjectResult<PROC_USER_LOGIN_DETAILS_Result2> PROC_USER_LOGIN_DETAILS(string uSER_NAME, string uSER_PASSWORD)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_USER_LOGIN_DETAILS_Result2>("PROC_USER_LOGIN_DETAILS", uSER_NAMEParameter, uSER_PASSWORDParameter);
        }
    
        public virtual ObjectResult<PROC_USER_ADDUPDATE_REQUIREMENT_Result2> PROC_USER_ADDUPDATE_REQUIREMENT(Nullable<int> uSER_REQUIREMENT_ID, string rEGISTRATION_NO, Nullable<int> rEQUIREMENT_ID, Nullable<int> cANDIDATE_STATUS, Nullable<bool> cURRENT_STATUS, string cREATED_BY)
        {
            var uSER_REQUIREMENT_IDParameter = uSER_REQUIREMENT_ID.HasValue ?
                new ObjectParameter("USER_REQUIREMENT_ID", uSER_REQUIREMENT_ID) :
                new ObjectParameter("USER_REQUIREMENT_ID", typeof(int));
    
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            var rEQUIREMENT_IDParameter = rEQUIREMENT_ID.HasValue ?
                new ObjectParameter("REQUIREMENT_ID", rEQUIREMENT_ID) :
                new ObjectParameter("REQUIREMENT_ID", typeof(int));
    
            var cANDIDATE_STATUSParameter = cANDIDATE_STATUS.HasValue ?
                new ObjectParameter("CANDIDATE_STATUS", cANDIDATE_STATUS) :
                new ObjectParameter("CANDIDATE_STATUS", typeof(int));
    
            var cURRENT_STATUSParameter = cURRENT_STATUS.HasValue ?
                new ObjectParameter("CURRENT_STATUS", cURRENT_STATUS) :
                new ObjectParameter("CURRENT_STATUS", typeof(bool));
    
            var cREATED_BYParameter = cREATED_BY != null ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_USER_ADDUPDATE_REQUIREMENT_Result2>("PROC_USER_ADDUPDATE_REQUIREMENT", uSER_REQUIREMENT_IDParameter, rEGISTRATION_NOParameter, rEQUIREMENT_IDParameter, cANDIDATE_STATUSParameter, cURRENT_STATUSParameter, cREATED_BYParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ALL_SPECIALIZATIONS_Result> PROC_GET_ALL_SPECIALIZATIONS(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ALL_SPECIALIZATIONS_Result>("PROC_GET_ALL_SPECIALIZATIONS", iDParameter);
        }
    
        public virtual ObjectResult<PROC_DOCUMENT_DOWNLOAD_Result> PROC_DOCUMENT_DOWNLOAD(string pASSPORT_NO, string rEGISTRATION_NO, string cONDITIONAL_OPERATOR)
        {
            var pASSPORT_NOParameter = pASSPORT_NO != null ?
                new ObjectParameter("PASSPORT_NO", pASSPORT_NO) :
                new ObjectParameter("PASSPORT_NO", typeof(string));
    
            var rEGISTRATION_NOParameter = rEGISTRATION_NO != null ?
                new ObjectParameter("REGISTRATION_NO", rEGISTRATION_NO) :
                new ObjectParameter("REGISTRATION_NO", typeof(string));
    
            var cONDITIONAL_OPERATORParameter = cONDITIONAL_OPERATOR != null ?
                new ObjectParameter("CONDITIONAL_OPERATOR", cONDITIONAL_OPERATOR) :
                new ObjectParameter("CONDITIONAL_OPERATOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_DOCUMENT_DOWNLOAD_Result>("PROC_DOCUMENT_DOWNLOAD", pASSPORT_NOParameter, rEGISTRATION_NOParameter, cONDITIONAL_OPERATORParameter);
        }
    
        public virtual ObjectResult<PROC_GET_EDIT_DETAILS_BY_REQUIREMENT_ID_Result4> PROC_GET_EDIT_DETAILS_BY_REQUIREMENT_ID(Nullable<int> rEQUIREMENT_ID)
        {
            var rEQUIREMENT_IDParameter = rEQUIREMENT_ID.HasValue ?
                new ObjectParameter("REQUIREMENT_ID", rEQUIREMENT_ID) :
                new ObjectParameter("REQUIREMENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_EDIT_DETAILS_BY_REQUIREMENT_ID_Result4>("PROC_GET_EDIT_DETAILS_BY_REQUIREMENT_ID", rEQUIREMENT_IDParameter);
        }
    
        public virtual int PROC_REQUIREMENT_DETAILS_INSERT(string cOMPANY_ID, Nullable<int> nO_OF_OPENINGS, Nullable<decimal> eXPERIENCE_FROM, Nullable<decimal> eXPERIENCE_TO, string jOB_DESCRIPTION, string gENDER_CODES, Nullable<int> aGE_FROM, Nullable<int> aGE_TO, string rELIGION_IDS, Nullable<int> iNTERVIEW_MODE_ID, string sPECIALIZATION_IDS, string pOSTING_PLACE, Nullable<int> cURRENCY_TYPE_ID, Nullable<int> bASIC_SALARY_RANGE_TO, Nullable<int> bASIC_SALARY_RANGE_FROM, Nullable<decimal> oVERTIME, Nullable<int> tRIP_PER_YEAR, Nullable<decimal> cONTACT_PERIOD, Nullable<decimal> wORKING_HOURS, Nullable<int> lEAVES_PER_YEAR, string rEMARK, Nullable<bool> iS_ACTIVE, string uSER_CODE, string cONTACT_PERSON, string jOB_TITLE, string aLLOWANCE_IDS, string lANGUAGES_IDS, string eDUCATION_IDS, string iNDUSTRY_IDS, string dESIGNATION_IDS, string cIRTIFICATION_IDS, ObjectParameter requirementID)
        {
            var cOMPANY_IDParameter = cOMPANY_ID != null ?
                new ObjectParameter("COMPANY_ID", cOMPANY_ID) :
                new ObjectParameter("COMPANY_ID", typeof(string));
    
            var nO_OF_OPENINGSParameter = nO_OF_OPENINGS.HasValue ?
                new ObjectParameter("NO_OF_OPENINGS", nO_OF_OPENINGS) :
                new ObjectParameter("NO_OF_OPENINGS", typeof(int));
    
            var eXPERIENCE_FROMParameter = eXPERIENCE_FROM.HasValue ?
                new ObjectParameter("EXPERIENCE_FROM", eXPERIENCE_FROM) :
                new ObjectParameter("EXPERIENCE_FROM", typeof(decimal));
    
            var eXPERIENCE_TOParameter = eXPERIENCE_TO.HasValue ?
                new ObjectParameter("EXPERIENCE_TO", eXPERIENCE_TO) :
                new ObjectParameter("EXPERIENCE_TO", typeof(decimal));
    
            var jOB_DESCRIPTIONParameter = jOB_DESCRIPTION != null ?
                new ObjectParameter("JOB_DESCRIPTION", jOB_DESCRIPTION) :
                new ObjectParameter("JOB_DESCRIPTION", typeof(string));
    
            var gENDER_CODESParameter = gENDER_CODES != null ?
                new ObjectParameter("GENDER_CODES", gENDER_CODES) :
                new ObjectParameter("GENDER_CODES", typeof(string));
    
            var aGE_FROMParameter = aGE_FROM.HasValue ?
                new ObjectParameter("AGE_FROM", aGE_FROM) :
                new ObjectParameter("AGE_FROM", typeof(int));
    
            var aGE_TOParameter = aGE_TO.HasValue ?
                new ObjectParameter("AGE_TO", aGE_TO) :
                new ObjectParameter("AGE_TO", typeof(int));
    
            var rELIGION_IDSParameter = rELIGION_IDS != null ?
                new ObjectParameter("RELIGION_IDS", rELIGION_IDS) :
                new ObjectParameter("RELIGION_IDS", typeof(string));
    
            var iNTERVIEW_MODE_IDParameter = iNTERVIEW_MODE_ID.HasValue ?
                new ObjectParameter("INTERVIEW_MODE_ID", iNTERVIEW_MODE_ID) :
                new ObjectParameter("INTERVIEW_MODE_ID", typeof(int));
    
            var sPECIALIZATION_IDSParameter = sPECIALIZATION_IDS != null ?
                new ObjectParameter("SPECIALIZATION_IDS", sPECIALIZATION_IDS) :
                new ObjectParameter("SPECIALIZATION_IDS", typeof(string));
    
            var pOSTING_PLACEParameter = pOSTING_PLACE != null ?
                new ObjectParameter("POSTING_PLACE", pOSTING_PLACE) :
                new ObjectParameter("POSTING_PLACE", typeof(string));
    
            var cURRENCY_TYPE_IDParameter = cURRENCY_TYPE_ID.HasValue ?
                new ObjectParameter("CURRENCY_TYPE_ID", cURRENCY_TYPE_ID) :
                new ObjectParameter("CURRENCY_TYPE_ID", typeof(int));
    
            var bASIC_SALARY_RANGE_TOParameter = bASIC_SALARY_RANGE_TO.HasValue ?
                new ObjectParameter("BASIC_SALARY_RANGE_TO", bASIC_SALARY_RANGE_TO) :
                new ObjectParameter("BASIC_SALARY_RANGE_TO", typeof(int));
    
            var bASIC_SALARY_RANGE_FROMParameter = bASIC_SALARY_RANGE_FROM.HasValue ?
                new ObjectParameter("BASIC_SALARY_RANGE_FROM", bASIC_SALARY_RANGE_FROM) :
                new ObjectParameter("BASIC_SALARY_RANGE_FROM", typeof(int));
    
            var oVERTIMEParameter = oVERTIME.HasValue ?
                new ObjectParameter("OVERTIME", oVERTIME) :
                new ObjectParameter("OVERTIME", typeof(decimal));
    
            var tRIP_PER_YEARParameter = tRIP_PER_YEAR.HasValue ?
                new ObjectParameter("TRIP_PER_YEAR", tRIP_PER_YEAR) :
                new ObjectParameter("TRIP_PER_YEAR", typeof(int));
    
            var cONTACT_PERIODParameter = cONTACT_PERIOD.HasValue ?
                new ObjectParameter("CONTACT_PERIOD", cONTACT_PERIOD) :
                new ObjectParameter("CONTACT_PERIOD", typeof(decimal));
    
            var wORKING_HOURSParameter = wORKING_HOURS.HasValue ?
                new ObjectParameter("WORKING_HOURS", wORKING_HOURS) :
                new ObjectParameter("WORKING_HOURS", typeof(decimal));
    
            var lEAVES_PER_YEARParameter = lEAVES_PER_YEAR.HasValue ?
                new ObjectParameter("LEAVES_PER_YEAR", lEAVES_PER_YEAR) :
                new ObjectParameter("LEAVES_PER_YEAR", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var uSER_CODEParameter = uSER_CODE != null ?
                new ObjectParameter("USER_CODE", uSER_CODE) :
                new ObjectParameter("USER_CODE", typeof(string));
    
            var cONTACT_PERSONParameter = cONTACT_PERSON != null ?
                new ObjectParameter("CONTACT_PERSON", cONTACT_PERSON) :
                new ObjectParameter("CONTACT_PERSON", typeof(string));
    
            var jOB_TITLEParameter = jOB_TITLE != null ?
                new ObjectParameter("JOB_TITLE", jOB_TITLE) :
                new ObjectParameter("JOB_TITLE", typeof(string));
    
            var aLLOWANCE_IDSParameter = aLLOWANCE_IDS != null ?
                new ObjectParameter("ALLOWANCE_IDS", aLLOWANCE_IDS) :
                new ObjectParameter("ALLOWANCE_IDS", typeof(string));
    
            var lANGUAGES_IDSParameter = lANGUAGES_IDS != null ?
                new ObjectParameter("LANGUAGES_IDS", lANGUAGES_IDS) :
                new ObjectParameter("LANGUAGES_IDS", typeof(string));
    
            var eDUCATION_IDSParameter = eDUCATION_IDS != null ?
                new ObjectParameter("EDUCATION_IDS", eDUCATION_IDS) :
                new ObjectParameter("EDUCATION_IDS", typeof(string));
    
            var iNDUSTRY_IDSParameter = iNDUSTRY_IDS != null ?
                new ObjectParameter("INDUSTRY_IDS", iNDUSTRY_IDS) :
                new ObjectParameter("INDUSTRY_IDS", typeof(string));
    
            var dESIGNATION_IDSParameter = dESIGNATION_IDS != null ?
                new ObjectParameter("DESIGNATION_IDS", dESIGNATION_IDS) :
                new ObjectParameter("DESIGNATION_IDS", typeof(string));
    
            var cIRTIFICATION_IDSParameter = cIRTIFICATION_IDS != null ?
                new ObjectParameter("CIRTIFICATION_IDS", cIRTIFICATION_IDS) :
                new ObjectParameter("CIRTIFICATION_IDS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_REQUIREMENT_DETAILS_INSERT", cOMPANY_IDParameter, nO_OF_OPENINGSParameter, eXPERIENCE_FROMParameter, eXPERIENCE_TOParameter, jOB_DESCRIPTIONParameter, gENDER_CODESParameter, aGE_FROMParameter, aGE_TOParameter, rELIGION_IDSParameter, iNTERVIEW_MODE_IDParameter, sPECIALIZATION_IDSParameter, pOSTING_PLACEParameter, cURRENCY_TYPE_IDParameter, bASIC_SALARY_RANGE_TOParameter, bASIC_SALARY_RANGE_FROMParameter, oVERTIMEParameter, tRIP_PER_YEARParameter, cONTACT_PERIODParameter, wORKING_HOURSParameter, lEAVES_PER_YEARParameter, rEMARKParameter, iS_ACTIVEParameter, uSER_CODEParameter, cONTACT_PERSONParameter, jOB_TITLEParameter, aLLOWANCE_IDSParameter, lANGUAGES_IDSParameter, eDUCATION_IDSParameter, iNDUSTRY_IDSParameter, dESIGNATION_IDSParameter, cIRTIFICATION_IDSParameter, requirementID);
        }
    
        public virtual int PROC_REQUIREMENT_DETAILS_UPDATE(Nullable<int> rEQUIREMENT_ID, string cOMPANY_ID, Nullable<int> nO_OF_OPENINGS, Nullable<decimal> eXPERIENCE_FROM, Nullable<decimal> eXPERIENCE_TO, string jOB_DESCRIPTION, string gENDER_CODES, Nullable<int> aGE_FROM, Nullable<int> aGE_TO, string rELIGION_IDS, Nullable<int> iNTERVIEW_MODE_ID, string sPECIALIZATION_IDS, string pOSTING_PLACE, Nullable<int> cURRENCY_TYPE_ID, Nullable<int> bASIC_SALARY_RANGE_TO, Nullable<int> bASIC_SALARY_RANGE_FROM, Nullable<decimal> oVERTIME, Nullable<int> tRIP_PER_YEAR, Nullable<decimal> cONTACT_PERIOD, Nullable<decimal> wORKING_HOURS, Nullable<int> lEAVES_PER_YEAR, string rEMARK, Nullable<bool> iS_ACTIVE, string uSER_CODE, string cONTACT_PERSON, string jOB_TITLE, string aLLOWANCE_IDS, string lANGUAGES_IDS, string eDUCATION_IDS, string iNDUSTRY_IDS, string dESIGNATION_IDS, string cIRTIFICATION_IDS)
        {
            var rEQUIREMENT_IDParameter = rEQUIREMENT_ID.HasValue ?
                new ObjectParameter("REQUIREMENT_ID", rEQUIREMENT_ID) :
                new ObjectParameter("REQUIREMENT_ID", typeof(int));
    
            var cOMPANY_IDParameter = cOMPANY_ID != null ?
                new ObjectParameter("COMPANY_ID", cOMPANY_ID) :
                new ObjectParameter("COMPANY_ID", typeof(string));
    
            var nO_OF_OPENINGSParameter = nO_OF_OPENINGS.HasValue ?
                new ObjectParameter("NO_OF_OPENINGS", nO_OF_OPENINGS) :
                new ObjectParameter("NO_OF_OPENINGS", typeof(int));
    
            var eXPERIENCE_FROMParameter = eXPERIENCE_FROM.HasValue ?
                new ObjectParameter("EXPERIENCE_FROM", eXPERIENCE_FROM) :
                new ObjectParameter("EXPERIENCE_FROM", typeof(decimal));
    
            var eXPERIENCE_TOParameter = eXPERIENCE_TO.HasValue ?
                new ObjectParameter("EXPERIENCE_TO", eXPERIENCE_TO) :
                new ObjectParameter("EXPERIENCE_TO", typeof(decimal));
    
            var jOB_DESCRIPTIONParameter = jOB_DESCRIPTION != null ?
                new ObjectParameter("JOB_DESCRIPTION", jOB_DESCRIPTION) :
                new ObjectParameter("JOB_DESCRIPTION", typeof(string));
    
            var gENDER_CODESParameter = gENDER_CODES != null ?
                new ObjectParameter("GENDER_CODES", gENDER_CODES) :
                new ObjectParameter("GENDER_CODES", typeof(string));
    
            var aGE_FROMParameter = aGE_FROM.HasValue ?
                new ObjectParameter("AGE_FROM", aGE_FROM) :
                new ObjectParameter("AGE_FROM", typeof(int));
    
            var aGE_TOParameter = aGE_TO.HasValue ?
                new ObjectParameter("AGE_TO", aGE_TO) :
                new ObjectParameter("AGE_TO", typeof(int));
    
            var rELIGION_IDSParameter = rELIGION_IDS != null ?
                new ObjectParameter("RELIGION_IDS", rELIGION_IDS) :
                new ObjectParameter("RELIGION_IDS", typeof(string));
    
            var iNTERVIEW_MODE_IDParameter = iNTERVIEW_MODE_ID.HasValue ?
                new ObjectParameter("INTERVIEW_MODE_ID", iNTERVIEW_MODE_ID) :
                new ObjectParameter("INTERVIEW_MODE_ID", typeof(int));
    
            var sPECIALIZATION_IDSParameter = sPECIALIZATION_IDS != null ?
                new ObjectParameter("SPECIALIZATION_IDS", sPECIALIZATION_IDS) :
                new ObjectParameter("SPECIALIZATION_IDS", typeof(string));
    
            var pOSTING_PLACEParameter = pOSTING_PLACE != null ?
                new ObjectParameter("POSTING_PLACE", pOSTING_PLACE) :
                new ObjectParameter("POSTING_PLACE", typeof(string));
    
            var cURRENCY_TYPE_IDParameter = cURRENCY_TYPE_ID.HasValue ?
                new ObjectParameter("CURRENCY_TYPE_ID", cURRENCY_TYPE_ID) :
                new ObjectParameter("CURRENCY_TYPE_ID", typeof(int));
    
            var bASIC_SALARY_RANGE_TOParameter = bASIC_SALARY_RANGE_TO.HasValue ?
                new ObjectParameter("BASIC_SALARY_RANGE_TO", bASIC_SALARY_RANGE_TO) :
                new ObjectParameter("BASIC_SALARY_RANGE_TO", typeof(int));
    
            var bASIC_SALARY_RANGE_FROMParameter = bASIC_SALARY_RANGE_FROM.HasValue ?
                new ObjectParameter("BASIC_SALARY_RANGE_FROM", bASIC_SALARY_RANGE_FROM) :
                new ObjectParameter("BASIC_SALARY_RANGE_FROM", typeof(int));
    
            var oVERTIMEParameter = oVERTIME.HasValue ?
                new ObjectParameter("OVERTIME", oVERTIME) :
                new ObjectParameter("OVERTIME", typeof(decimal));
    
            var tRIP_PER_YEARParameter = tRIP_PER_YEAR.HasValue ?
                new ObjectParameter("TRIP_PER_YEAR", tRIP_PER_YEAR) :
                new ObjectParameter("TRIP_PER_YEAR", typeof(int));
    
            var cONTACT_PERIODParameter = cONTACT_PERIOD.HasValue ?
                new ObjectParameter("CONTACT_PERIOD", cONTACT_PERIOD) :
                new ObjectParameter("CONTACT_PERIOD", typeof(decimal));
    
            var wORKING_HOURSParameter = wORKING_HOURS.HasValue ?
                new ObjectParameter("WORKING_HOURS", wORKING_HOURS) :
                new ObjectParameter("WORKING_HOURS", typeof(decimal));
    
            var lEAVES_PER_YEARParameter = lEAVES_PER_YEAR.HasValue ?
                new ObjectParameter("LEAVES_PER_YEAR", lEAVES_PER_YEAR) :
                new ObjectParameter("LEAVES_PER_YEAR", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var uSER_CODEParameter = uSER_CODE != null ?
                new ObjectParameter("USER_CODE", uSER_CODE) :
                new ObjectParameter("USER_CODE", typeof(string));
    
            var cONTACT_PERSONParameter = cONTACT_PERSON != null ?
                new ObjectParameter("CONTACT_PERSON", cONTACT_PERSON) :
                new ObjectParameter("CONTACT_PERSON", typeof(string));
    
            var jOB_TITLEParameter = jOB_TITLE != null ?
                new ObjectParameter("JOB_TITLE", jOB_TITLE) :
                new ObjectParameter("JOB_TITLE", typeof(string));
    
            var aLLOWANCE_IDSParameter = aLLOWANCE_IDS != null ?
                new ObjectParameter("ALLOWANCE_IDS", aLLOWANCE_IDS) :
                new ObjectParameter("ALLOWANCE_IDS", typeof(string));
    
            var lANGUAGES_IDSParameter = lANGUAGES_IDS != null ?
                new ObjectParameter("LANGUAGES_IDS", lANGUAGES_IDS) :
                new ObjectParameter("LANGUAGES_IDS", typeof(string));
    
            var eDUCATION_IDSParameter = eDUCATION_IDS != null ?
                new ObjectParameter("EDUCATION_IDS", eDUCATION_IDS) :
                new ObjectParameter("EDUCATION_IDS", typeof(string));
    
            var iNDUSTRY_IDSParameter = iNDUSTRY_IDS != null ?
                new ObjectParameter("INDUSTRY_IDS", iNDUSTRY_IDS) :
                new ObjectParameter("INDUSTRY_IDS", typeof(string));
    
            var dESIGNATION_IDSParameter = dESIGNATION_IDS != null ?
                new ObjectParameter("DESIGNATION_IDS", dESIGNATION_IDS) :
                new ObjectParameter("DESIGNATION_IDS", typeof(string));
    
            var cIRTIFICATION_IDSParameter = cIRTIFICATION_IDS != null ?
                new ObjectParameter("CIRTIFICATION_IDS", cIRTIFICATION_IDS) :
                new ObjectParameter("CIRTIFICATION_IDS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_REQUIREMENT_DETAILS_UPDATE", rEQUIREMENT_IDParameter, cOMPANY_IDParameter, nO_OF_OPENINGSParameter, eXPERIENCE_FROMParameter, eXPERIENCE_TOParameter, jOB_DESCRIPTIONParameter, gENDER_CODESParameter, aGE_FROMParameter, aGE_TOParameter, rELIGION_IDSParameter, iNTERVIEW_MODE_IDParameter, sPECIALIZATION_IDSParameter, pOSTING_PLACEParameter, cURRENCY_TYPE_IDParameter, bASIC_SALARY_RANGE_TOParameter, bASIC_SALARY_RANGE_FROMParameter, oVERTIMEParameter, tRIP_PER_YEARParameter, cONTACT_PERIODParameter, wORKING_HOURSParameter, lEAVES_PER_YEARParameter, rEMARKParameter, iS_ACTIVEParameter, uSER_CODEParameter, cONTACT_PERSONParameter, jOB_TITLEParameter, aLLOWANCE_IDSParameter, lANGUAGES_IDSParameter, eDUCATION_IDSParameter, iNDUSTRY_IDSParameter, dESIGNATION_IDSParameter, cIRTIFICATION_IDSParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ADVERTISEMENT_DATA_Result5> PROC_GET_ADVERTISEMENT_DATA(Nullable<int> aDVERTISEMENT_ID)
        {
            var aDVERTISEMENT_IDParameter = aDVERTISEMENT_ID.HasValue ?
                new ObjectParameter("ADVERTISEMENT_ID", aDVERTISEMENT_ID) :
                new ObjectParameter("ADVERTISEMENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ADVERTISEMENT_DATA_Result5>("PROC_GET_ADVERTISEMENT_DATA", aDVERTISEMENT_IDParameter);
        }
    
        public virtual ObjectResult<string> PROC_CHECKDUPLICATE_USER(Nullable<int> uSER_TYPE_ID, string fIRST_NAME, string lAST_NAME, Nullable<System.DateTime> dATE_OF_BIRTH, string pLACE_OF_BIRTH)
        {
            var uSER_TYPE_IDParameter = uSER_TYPE_ID.HasValue ?
                new ObjectParameter("USER_TYPE_ID", uSER_TYPE_ID) :
                new ObjectParameter("USER_TYPE_ID", typeof(int));
    
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var dATE_OF_BIRTHParameter = dATE_OF_BIRTH.HasValue ?
                new ObjectParameter("DATE_OF_BIRTH", dATE_OF_BIRTH) :
                new ObjectParameter("DATE_OF_BIRTH", typeof(System.DateTime));
    
            var pLACE_OF_BIRTHParameter = pLACE_OF_BIRTH != null ?
                new ObjectParameter("PLACE_OF_BIRTH", pLACE_OF_BIRTH) :
                new ObjectParameter("PLACE_OF_BIRTH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_CHECKDUPLICATE_USER", uSER_TYPE_IDParameter, fIRST_NAMEParameter, lAST_NAMEParameter, dATE_OF_BIRTHParameter, pLACE_OF_BIRTHParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ALL_CITIES_Result1> PROC_GET_ALL_CITIES(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ALL_CITIES_Result1>("PROC_GET_ALL_CITIES", iDParameter);
        }
    
        public virtual ObjectResult<PROC_GET_ALL_STATES_Result1> PROC_GET_ALL_STATES(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GET_ALL_STATES_Result1>("PROC_GET_ALL_STATES", iDParameter);
        }
    
        public virtual ObjectResult<PROC_REQUIREMENT_SEARCH_RESULT_Result5> PROC_REQUIREMENT_SEARCH_RESULT(string cOMPANY_ID, Nullable<bool> iS_ACTIVE, string cLIENT_NAME, string jOB_TITLE)
        {
            var cOMPANY_IDParameter = cOMPANY_ID != null ?
                new ObjectParameter("COMPANY_ID", cOMPANY_ID) :
                new ObjectParameter("COMPANY_ID", typeof(string));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var cLIENT_NAMEParameter = cLIENT_NAME != null ?
                new ObjectParameter("CLIENT_NAME", cLIENT_NAME) :
                new ObjectParameter("CLIENT_NAME", typeof(string));
    
            var jOB_TITLEParameter = jOB_TITLE != null ?
                new ObjectParameter("JOB_TITLE", jOB_TITLE) :
                new ObjectParameter("JOB_TITLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_REQUIREMENT_SEARCH_RESULT_Result5>("PROC_REQUIREMENT_SEARCH_RESULT", cOMPANY_IDParameter, iS_ACTIVEParameter, cLIENT_NAMEParameter, jOB_TITLEParameter);
        }
    
        public virtual ObjectResult<string> PROC_CHECK_DUPLICATEREQUIREMENT(string cOMPANY_ID, string cONTACT_PERSON, string jOB_TITLE)
        {
            var cOMPANY_IDParameter = cOMPANY_ID != null ?
                new ObjectParameter("COMPANY_ID", cOMPANY_ID) :
                new ObjectParameter("COMPANY_ID", typeof(string));
    
            var cONTACT_PERSONParameter = cONTACT_PERSON != null ?
                new ObjectParameter("CONTACT_PERSON", cONTACT_PERSON) :
                new ObjectParameter("CONTACT_PERSON", typeof(string));
    
            var jOB_TITLEParameter = jOB_TITLE != null ?
                new ObjectParameter("JOB_TITLE", jOB_TITLE) :
                new ObjectParameter("JOB_TITLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_CHECK_DUPLICATEREQUIREMENT", cOMPANY_IDParameter, cONTACT_PERSONParameter, jOB_TITLEParameter);
        }
    }
}
